# Generated by Django 3.0.6 on 2020-06-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_partner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='organisation_Name',
            new_name='organisationName',
        ),
    ]
