# Generated by Django 3.0.6 on 2020-06-24 08:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200624_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=100)),
                ('contact_Number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('father_Name', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('PAN_Number', models.CharField(blank=True, max_length=10)),
                ('aadhar_Number', models.BigIntegerField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('last_Salary', models.BigIntegerField(blank=True)),
                ('last_Company', models.CharField(blank=True, max_length=100)),
                ('upload_Resume', models.FileField(upload_to='documents1/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
